# Generated by Django 2.2.13 on 2021-02-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_bsensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('s_date', models.DateTimeField(blank=True, null=True)),
                ('locate', models.CharField(blank=True, max_length=50, null=True)),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('degree', models.FloatField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, max_length=20, null=True)),
                ('y', models.FloatField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sensor_data',
                'managed': False,
            },
        ),
    ]
